import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavItem from "@/components/NavItem";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ul className="flex justify-between px-40 nav-list">
          <NavItem href={"about"}>About</NavItem>
          <NavItem href={"/"}>Home</NavItem>
          <NavItem href={"/dashboard"}>Dashboard</NavItem>
          <NavItem href={"/users"}>Users</NavItem>
        </ul>
        {children}
      </body>
    </html>
  );
}
